name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff check
        uses: astral-sh/ruff-action@v1
      - name: Ruff format
        uses: astral-sh/ruff-action@v1
        with:
          args: format