name: Test
on: [push, pull_request]

jobs:
  pytest:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install dependencies
        run: uv sync --all-extras --dev --default-index https://pypi.org/simple
      
      - name: Run tests
        run: uv run pytest
      
      - name: Generate coverage badge
        run: |
          uv tool install genbadge[coverage]
          uv run genbadge coverage -i cov.xml -o assets/coverage-badge.svg
      
      - name: Commit coverage badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/coverage-badge.svg
          git commit -m "📊 coverage: update coverage badge" || echo "No changes to commit"
      
      - name: Push coverage badge
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}